apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
  labels:
    group: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: default
  labels:
    group: developers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditor-user
  namespace: default
  labels:
    group: auditors